name = "visit-counter"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "VISITS"
id = "be13965d5c6b4013836b2186d762b0d0"

[triggers]
# Để dùng custom route cryss.info/api/visits*
# Cần thêm route trong Cloudflare dashboard:
#   cryss.info/api/visits* -> visit-counter
